import 'package:flutter/material.dart';

class AppColorSchemes {
  const AppColorSchemes._();

  /// iOS 26 Liquid Glass 亮色：雾白背景 + 克制蓝紫主色。
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF2F6BFF),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFDDE7FF),
    onPrimaryContainer: Color(0xFF123067),
    secondary: Color(0xFF6E7BFF),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE6E8FF),
    onSecondaryContainer: Color(0xFF24285F),
    tertiary: Color(0xFF2BA8C7),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFD8F5FB),
    onTertiaryContainer: Color(0xFF073B49),
    error: Color(0xFFD92D20),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFE2DE),
    onErrorContainer: Color(0xFF7A1410),
    surface: Color(0xFFF7F9FE),
    onSurface: Color(0xFF111827),
    surfaceDim: Color(0xFFE4E8F2),
    surfaceBright: Color(0xFFFFFFFF),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF3F6FC),
    surfaceContainer: Color(0xFFEDF2FA),
    surfaceContainerHigh: Color(0xFFE7ECF6),
    surfaceContainerHighest: Color(0xFFDDE4F0),
    onSurfaceVariant: Color(0xFF4B5563),
    outline: Color(0xFF94A3B8),
    outlineVariant: Color(0xFFC9D3E3),
    shadow: Color(0x330F172A),
    scrim: Color(0x990F172A),
    inverseSurface: Color(0xFF1F2937),
    onInverseSurface: Color(0xFFF9FAFB),
    inversePrimary: Color(0xFFAEC4FF),
  );

  /// iOS 26 Liquid Glass 暗色：午夜蓝灰背景 + 柔和蓝紫主色，避免纯黑和霓虹。
  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFAEC4FF),
    onPrimary: Color(0xFF102A5F),
    primaryContainer: Color(0xFF23498F),
    onPrimaryContainer: Color(0xFFE5ECFF),
    secondary: Color(0xFFC6CBFF),
    onSecondary: Color(0xFF282D69),
    secondaryContainer: Color(0xFF3D438D),
    onSecondaryContainer: Color(0xFFE9EAFF),
    tertiary: Color(0xFF7ADDEF),
    onTertiary: Color(0xFF063B48),
    tertiaryContainer: Color(0xFF145B6A),
    onTertiaryContainer: Color(0xFFD8F8FF),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF0F1724),
    onSurface: Color(0xFFE8ECF3),
    surfaceDim: Color(0xFF0A1020),
    surfaceBright: Color(0xFF263244),
    surfaceContainerLowest: Color(0xFF070C16),
    surfaceContainerLow: Color(0xFF121A2A),
    surfaceContainer: Color(0xFF182235),
    surfaceContainerHigh: Color(0xFF202B3F),
    surfaceContainerHighest: Color(0xFF2A3650),
    onSurfaceVariant: Color(0xFFC3CBD8),
    outline: Color(0xFF7F8A9E),
    outlineVariant: Color(0xFF3C465B),
    shadow: Color(0x99000000),
    scrim: Color(0xCC000000),
    inverseSurface: Color(0xFFE8ECF3),
    onInverseSurface: Color(0xFF111827),
    inversePrimary: Color(0xFF2F6BFF),
  );
}
